### ISSUE TITLE
Autocomplete i Bootstrap

### ISSUE THREAD

**Issue by mik-laj** [ad-m/django-atom#3]
Dzień dobry, 
Warto rozważyć doklejenie kodu CSS

``` css
.form-group .autocomplete-light-widget{
  width:100%;
}
```

do biblioteki. 
Naprawia to zachowanie się pola wprowadzania tekstu w formularzach od Bootstrapa, jednocześnie nie psuje autosugestii.

Z miłością :kissing_heart:
